### ISSUE TITLE
Matter Analyzer and Matter Decomposer don't have animated sides when running.

### ISSUE THREAD

**Issue by vanmuur** [vanmuur/matter-overdrive-fhe#6]
Right now, they are always animated, or always static.

**Comment by ibonny** [comment]
Partially fixed. It works, but in fixing that, it broke upgrades.

**Comment by vanmuur** [comment]
So, breakBlock(), which is required in the main Block class for each machine, isn't calling super(), which probably sets up proper saving of the upgrades when the block is broken. Try adding this.

**Comment by vanmuur** [comment]
The inscriber also doesn't animate when running.

**Comment by vanmuur** [comment]
I've been able to get this to work using custom setState() commands, but they have a weird side-effect of affecting how the sound mufflers work. I think it might have to do with saving the state of the inventory, but I don't know for sure.

**Comment by vanmuur** [comment]
This has been fixed.
